is_debug: false
project_name: blockchainEvoting
api_string: /api
secret_key: SECRET_KEY
api_key: API_KEY
access_token_expire_minutes: 10080  # 7 days
password_length: 12


redis_host: redis
redis_port: 6379

ethereum:
  network: sepolia
  rpc_connection_timeout: 60
  cold_storage_address: ""
  hot_wallet_address: ""
  private_key: ""
  broadcast_interval: 5
  min_deposit_amount: 0.00001
  min_withdrawal_amount: 0.00001
  confirmations_count: 1
  fee_priority: standard
  rpc_url: ""
  voting_contract_address: "0x9b08AfE17d6683b6605B5F8e8a1E7489545D67eF"
  always_restart_interval: 60
  confirmation_blocks: 5
  scanning_blocks_max: 50
  polling_interval: 30
  speedy_polling_interval: 5
